image: docker:git
services:
- docker:dind
variables:
  DOCKER_TLS_CERTDIR: ""

build:
  tags:
    - docker-atp
  only:
    - master
  script:
    - docker build -t test .
    - docker run --privileged test  # btrfs mounting requires --privileged

