image: docker

stages:
  - build

build:
  stage: build
  tags:
    - docker-atp
  only:
    - master
  script:
    - docker build -t test .
    - docker run --privileged test  # btrfs mounting requires --privileged
