image: ubuntu:xenial

stages:
  - test

test:
  stage: test
  tags:
    - docker-atp
  only:
    - master
  script:
    - ./bootstrap/setup_general.sh
    - ./bootstrap/setup_links_gitlab.sh
    - ./bootstrap/setup_python.sh
    - ./bootstrap/btrfs_install.sh
    - ./bootstrap/volumes_create.sh
    - ./bootstrap/volumes_mount.sh
    - ./tests/autotest.sh
